# templates/applications.yaml
{{- range .Values.appList }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ . }}"
  namespace: {{ $.Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  info:
  - name: 'Trigger-Pre:'
    value: >-
      http://34.28.94.32:8080/
  project: default
  source:
    repoURL: {{ $.Values.repoUrl }}
    targetRevision: {{ $.Values.targetRevision }}
    path: "helm-charts"
    helm:
      valueFiles:
        - "/manifests/{{ . }}/{{ $.Values.env.name }}/immutable/values.yaml"
        - "/manifests/{{ . }}/{{ $.Values.env.name }}/configmap/configmap.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.appNamespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
{{- end }}