apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: priyankapractice
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sarsatis/helm-charts.git
    targetRevision: HEAD
    path: charts/priyankalearnings
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true