apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: jenkins-pipeline
spec:
  volumes:
    - name: sharedvolume
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: dockercred
        items:
          - key: .dockerconfigjson
            path: config.json
  serviceAccountName: jenkins
  securityContext:
    runAsUser: 0
  containers:
    - name: helm
      image: "justinrlee/helm3"
      ttyEnabled: true
      command:
        - sleep
      args:
        - "9999999"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - "9999999"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
    - name: gradle
      image: gradle
      imagePullPolicy: Always
      ttyEnabled: true
      command:
        - sleep
      args:
        - 99d
    - name: python
      image: python:latest
      imagePullPolicy: Always
      command:
        - sleep
        - "1000"
      tty: true