apiVersion: apps/v1
kind: Deployment
metadata:
#  annotations:
#    "app.kubernetes.io/managed-by" : "Helm"
#    "meta.helm.sh/release-namespace": "jenkins"
#    "meta.helm.sh/release-name": "priyankalearnings"
  creationTimestamp: null
  labels:
    app: "{{ .Values.appName }}"
  name: "{{ .Values.appName }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.appName }}"
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: "{{ .Values.appName }}"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: "{{ .Values.appName }}"
          resources: {}
status: {}
