apiVersion: v1
kind: Service
metadata:
#  annotations:
#    "app.kubernetes.io/managed-by": "Helm"
#    "meta.helm.sh/release-namespace": "jenkins"
#    "meta.helm.sh/release-name": "priyankalearnings"
  creationTimestamp: null
  labels:
    app: "{{ .Values.appName }}"
  name: "{{ .Values.appName }}"
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: "{{ .Values.appName }}"
  type: ClusterIP
status:
  loadBalancer: {}
