apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.appName }}"
  name: "{{ .Values.appName }}"
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: "{{ .Values.appName }}"
  type: ClusterIP
status:
  loadBalancer: {}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: {{ .Values.appName }}-preview
#   name: {{ .Values.appName }}-preview
# spec:
#   ports:
#     - port: 8080
#       protocol: TCP
#       targetPort: 8080
#   selector:
#     app: {{ .Values.appName }}
#   type: ClusterIP
# status:
#   loadBalancer: {}