---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - '*'
  gateways:
  - priyanka-gateway
  http:
{{ if eq .Values.canary "sa" }}
  - match:
    - uri:
        prefix: /app1
    route:
      - destination:
          host: {{ .Release.Name }}
          port:
            number: 8080
{{ else if eq .Values.canary "as" }}
  - match:
    - uri:
        prefix: /app1
      headers:
        jira-id:
          exact: {{ .Values.jiraId }}
    route:
      - destination:
          host: {{ .Release.Name }}
          port:
            number: 8080
{{ end }}