apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - '*'
  gateways:
  - priyanka-gateway
  http:
  - match:
    - uri:
        exact: /app1/hello
    route:
      - destination:
          host: priyankalearnings
          port:
            number: 8080