apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - '*'
  gateways:
  - priyanka-gateway
  http:
{{- if eq .Values.canary "False" }}
  - match:
    - uri:
        prefix: /app1
    route:
      - destination:
          host: {{ .Release.Name }}
          port:
            number: 8080
{{- else  }}
  - match:
    - uri:
        prefix: /app1
      headers:
        jira-id:
          exact: {{ .Values.jiraId | quote }}
    route:
      - destination:
          host: {{ .Release.Name }}
          port:
            number: 8080
{{- end }}