apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - '*'
  gateways:
  - priyanka-gateway
  http:
  - match:
    - uri:
        prefix: /app1
    route:
      - destination:
          host: {{ .Release.Name }}
          port:
            number: 8080