apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-environments
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: sarsatis
          repo: helm-charts
          tokenRef:
            secretName: github-token
            key: token
          # appSecretName: private-repo-creds
          labels:
            - preview
        requeueAfterSeconds: 15
  template:
    metadata:
      name: "simple-deployment-{{branch}}-{{number}}"
    spec:
      source:
        repoURL: https://github.com/sarsatis/helm-charts.git
        targetRevision: "{{head_sha}}"
        path: charts/helm-charts
        helm:
          valueFiles:
            - "/manifests/solar-system/values.yaml"
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      destination:
        server: https://kubernetes.default.svc
        namespace: "simple-deployment-{{branch}}-{{number}}"
