# Default values for springboot-demoweb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

appName: rtlpropagation-sb

image:
  repository: sarthaksatish/rtlpropagation-sb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: b9655cac00d8d357e2db5ad0834fa65655d9f4ab-2