apiVersion: batch/v1
kind: Job
metadata:
  generateName: trigger-rtl-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-polict: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: trigger-rtl-container
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never