apiVersion: apps/v1
kind: Deployment
metadata:
#  annotations:
#    "app.kubernetes.io/managed-by" : "Helm"
#    "meta.helm.sh/release-namespace": "jenkins"
#    "meta.helm.sh/release-name": "priyankalearnings"
  creationTimestamp: null
  labels:
    app: priyankalearning
  name: priyankalearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priyankalearning
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: priyankalearning
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: priyankalearnings
          resources: {}
status: {}
