# Default values for springboot-demoweb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

appName: employeemanagement

image:
  repository: sarthaksatish/employeemanagement
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: cf0cf5d739432245851301f82ef5572360fa0a5f-5

dbname: employees
