apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: priyankapractice
  namespace: argocd
spec:
  generators:
    # Generator for apps that should deploy to all cluster.
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: dev
              values:
                env: dev
                targetRevision: main
                project: default
          # - list:
          #     elements:
          #       - appName: priyankapractice
          #       - appName: solar-system
          #       - appName: priyankalearnings
          - git:
              repoURL: https://github.com/sarsatis/helm-charts.git
              revision: main
              directories:
                # - path: /manifests/[priyankapractice|priyankalearnings]
                #   exclude: true
                - path: manifests/*

    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: sit
              values:
                env: sit
                targetRevision: main
                project: default
          - list:
              elements:
                - appName: priyankapractice
                - appName: solar-system
                - appName: priyankalearnings
  template:
    metadata:
      name: "{{path.basename}}-{{values.env}}"
    spec:
      project: "{{values.project}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/sarsatis/helm-charts.git
        targetRevision: "{{values.targetRevision}}"
        path: charts/helm-charts
        helm:
          valueFiles:
            - "/manifests/{{path.basename}}/values-{{values.env}}.yaml"
      destination:
        server: "{{server}}"
        namespace: argocd
