apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: priyankapractice
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: cluster1
        url: https://kubernetes.default.svc
        env: default
  template:
    metadata:
      name: 'priyankapractice-{{env}}'
    spec:
      project: '{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/sarsatis/helm-charts.git
        targetRevision: listgenerator
        path: charts/helm-charts
        helm:
          valueFiles:
            - "/manifests/priyankapractice/values.yaml"
      destination:
        server: '{{url}}'
        namespace: argocd