apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: priyankapractice
  namespace: argocd
spec:
  generators:
    # Generator for apps that should deploy to all cluster.
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: dev
              values:
                env: dev
                url: https://kubernetes.default.svc
                targetRevision: clustergenerator
                project: default
          - list:
              elements:
                - appName: priyankapractice
                - appName: solar-system
  template:
    metadata:
      name: {{appName}}-{{values.env}}
    spec:
      project: '{{values.project}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/sarsatis/helm-charts.git
        targetRevision: '{{values.targetRevision}}'
        path: charts/helm-charts
        helm:
          valueFiles:
            - "/manifests/{{appName}}/values-{{values.env}}.yaml"
      destination:
        server: '{{values.url}}'
        namespace: argocd

