apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: solar-system
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: cluster1
        url: https://kubernetes.default.svc
        env: bld
    #  - cluster: cluster2
    #     url: https://api.cluster2.chx.osecloud.com:6443
    #   - cluster: cluster3
    #     url: https://api.cluster3.chx.osecloud.com:6443
  template:
    metadata:
      name: 'solar-system-{{env}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/sarsatis/helm-charts.git
        targetRevision: applicationset
        path: charts/helm-charts
        helm:
          valueFiles:
            - "/manifests/solar-system/values.yaml"
      destination:
        server: '{{url}}'
        namespace: argocd
# ---

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: solar-system
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/sarsatis/helm-charts.git
#     targetRevision: HEAD
#     path: charts/helm-charts
#     helm:
#       valueFiles:
#         - "/manifests/solar-system/values.yaml"
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: argocd
#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true  
#     automated:
#       prune: true
#       selfHeal: true