apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: solar-system
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: cluster1
        url: https://kubernetes.default.svc
        env: default
  template:
    metadata:
      name: 'solar-system-{{env}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/sarsatis/helm-charts.git
        targetRevision: clustergenerator
        path: charts/helm-charts
        helm:
          valueFiles:
            - "/manifests/solar-system/values-{{env}}.yaml"
      destination:
        server: '{{url}}'
        namespace: argocd