# Default values for springboot-demoweb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

appName: solar-system

image:
  repository: sarthaksatish/solar-system
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 46-a3c3be92e2b7d1e27bd5a9319f22de26c1027254

